version: "3"

services:
  chat-app:
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: >
      sh -c 'yarn run start:dev'